# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opentree < Formula
  desc "Git worktree manager CLI"
  homepage "https://github.com/axelgar/opentree"
  version "0.1.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axelgar/opentree/releases/download/v0.1.22/opentree_0.1.22_darwin_amd64.tar.gz"
      sha256 "8068ee7b9eac0f900a0c14b26418f7654c09b970f175ef84e9d27007dbaf7a92"

      define_method(:install) do
        bin.install "opentree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axelgar/opentree/releases/download/v0.1.22/opentree_0.1.22_darwin_arm64.tar.gz"
      sha256 "d1ea92a94acea1613db2bd807589d0ba81abb2a77c0dfebe22237e967db1754c"

      define_method(:install) do
        bin.install "opentree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/axelgar/opentree/releases/download/v0.1.22/opentree_0.1.22_linux_amd64.tar.gz"
      sha256 "fad2f50068f9be39b15aad7ddb445c309431a3501a204e95ca7d134bd465a736"
      define_method(:install) do
        bin.install "opentree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axelgar/opentree/releases/download/v0.1.22/opentree_0.1.22_linux_arm64.tar.gz"
      sha256 "cc67c45d84c3c3c52a45b6f9ee70b169a5a13b964244b7a3e6c78114ba25cef2"
      define_method(:install) do
        bin.install "opentree"
      end
    end
  end
end
