# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentree" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "90497f0a2b214d76c1650d3f2955bf048434d85f42485defc1d08c5b40abb28b"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12f986cf21f26c2a03284044a039f26f93be74de85273f6f703b1e6052901403"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1994e7c591a395c714a82b802acc64967721ab44bdbf8d8608e4381aee74819a"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3069f21f068ecb2d9d9bfe9849d2887a5d6a91c93422e348e973498c35b9495d"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_arm64.tar.gz"
    end
  end

  name "opentree"
  desc "Git worktree manager CLI"
  homepage "https://github.com/axelgar/opentree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentree"]
    end
  end

  # No zap stanza required

end
