# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentree" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "4a932e127ba6dcd76d9adbba82a484ea09bc3d2acdcea3b8963f41869fad2d77"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59b4a12e6e41dcde3ea48678c677dd96b65b573e0598ff89b63152515eac6710"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cbf6d2aa4ae04901e21dfcf5600ae5962d3f6ce986b3b2191f1434d52bb18815"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "db3e646c6931bba095a190e622a4f01851aa5c52aa8578bd063d72a7f33cd585"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opentree"
  desc "Git worktree manager CLI"
  homepage "https://github.com/axelgar/opentree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentree"]
    end
  end

  # No zap stanza required
end
