# This file was generated by GoReleaser. DO NOT EDIT.
cask "opentree" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "0fc635e90455172b7c114b39d773829b48de298169d95c79856c828d989d30eb"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e1d947d6036e771e1bfe752e1c5e80b05d523808ee198ad9634c5ef0770ecad"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "acb50825c22b02d088061fc80f4ba6475d96cc094162aa426f0990ab4616158b"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4ea6ec30e1f44fbaf1b804d28f16b6ff99bb1919c2c369694461063063c883a"
      url "https://github.com/axelgar/opentree/releases/download/v#{version}/opentree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opentree"
  desc "Git worktree manager CLI"
  homepage "https://github.com/axelgar/opentree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opentree"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opentree"]
    end
  end

  # No zap stanza required
end
